{{- if (include "kubeflow.katib.enabled" . | eq "true") -}}
{{- if .Values.dbmanager.database.type | eq "postgres" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-postgres
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
{{- end }}
{{- end }}