{{- if .Values.database.type | eq "postgres" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.database.credentials.name }}
{{- with .Values.database.credentials.secret }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}