{{- if (include "kubeflow.katib.controller.enabled" . | eq "true") -}}

{{- $autoscalingEnabled := include "kubeflow.katib.controller.autoscaling.enabled" . -}}
{{- $replicas := include "kubeflow.katib.controller.autoscaling.minReplicas" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "kubeflow.katib.controller.labels" . | nindent 4 }}
  name: {{ include "kubeflow.katib.controller.name" . }}
  namespace: {{ include "kubeflow.namespace" . }}
spec:
  {{- if (eq $autoscalingEnabled "false") }}
  replicas: {{ $replicas }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "kubeflow.katib.controller.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "kubeflow.katib.controller.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: {{ include "kubeflow.katib.controller.baseName" . }}
          image: {{ include "kubeflow.katib.controller.image" . }} # docker.io/kubeflowkatib/katib-controller
          command: ["./katib-controller"]
          args:
            - --katib-config=/katib-config.yaml
          ports:
            - containerPort: 8443
              name: webhook
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 18080
              name: healthz
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          env:
            - name: KATIB_CORE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /tmp/cert
              name: cert
              readOnly: true
            - mountPath: /katib-config.yaml
              name: katib-config
              subPath: katib-config.yaml
              readOnly: true
      {{- with .Values.katib.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubeflow.katib.controller.serviceAccountName" . }}
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: katib-webhook-cert
        - name: katib-config
          configMap:
            name: katib-config
{{- end }}