{{- if (include "kubeflow.katib.enabled" . | eq "true") -}}
{{- if (include "kubeflow.katib.controller.enabled" . | eq "true") -}}
---
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.katib.controller.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kubeflow.katib.controller.labels" . | nindent 4 }}
  name: {{ include "kubeflow.katib.controller.svc.name" . }}
  namespace: {{ include "kubeflow.namespace" . }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
      name: webhook
    - name: metrics
      port: 8080
      targetPort: 8080
    - name: healthz
      port: 18080
      targetPort: 18080
  selector:
    {{- include "kubeflow.katib.controller.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}