apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubeflow.tensorboard.controller.name" . }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - {{ include "kubeflow.tensorboard.controller.name" . }}
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - {{ include "kubeflow.istioIntegration.name" . }}
      ports:
        - protocol: TCP
          port: {{ include "kubeflow.tensorboard.tensorboardsWebApp.svc.targetPort" . }}
  policyTypes:
    - Ingress
