{{- if (include "kubeflow.katib.enabled" . | eq "true") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: katib-config
data:
  katib-config.yaml: |
    ---
    apiVersion: config.kubeflow.org/v1beta1
    kind: KatibConfig
    {{ .Values.katib.config | toYaml | nindent 4 }}
{{- end }}