---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: katib-webhook-cert
spec:
  isCA: true
  commonName: {{ .Values.controller.name }}.{{ .Release.Namespace }}.svc
  dnsNames:
    - {{ .Values.controller.name }}.{{- .Release.Namespace }}.svc
    - {{ .Values.controller.name }}.{{- .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: katib-selfsigned-issuer
  secretName: katib-webhook-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: katib-selfsigned-issuer
spec:
  selfSigned: {}
