{{- if .Values.database.secret.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.database.secret.name }}
{{- with .Values.database.secret.data }}
data:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}