{{- if (include "kubeflow.katib.enabled" . | eq "true") -}}
{{- if .Values.dbmanager.database.secret.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.dbmanager.database.secret.name }}
{{- with .Values.dbmanager.database.secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}