enabled: true
clusterDomain: cluster.local
defaults:
  image:
    registry: docker.io
#    tag: "latest"
    tag: v0.16.0
    pullPolicy: IfNotPresent
  autoscaling:
    # If autoscaling is disabled, replica count for a component is equal to minReplicas.
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  podDisruptionBudget: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints:
  terminationGracePeriodSeconds:
  containerSecurityContext:
controller:
  enabled: true
  name: katib-controller
  image:
    repository: kubeflowkatib/katib-controller
    registryOverwrite:
    tagOverwrite:
    pullPolicyOverwrite:
  autoscaling:
    # If autoscaling is disabled, replica count for a component is equal to minReplicas.
    enabled:
    minReplicas:
    maxReplicas:
    targetCPUUtilizationPercentage:
    targetMemoryUtilizationPercentage:
  service:
    create: true
    annotations:
      prometheus.io/port: "8080"
      prometheus.io/scheme: http
      prometheus.io/scrape: "true"
  serviceAccount:
    create: true
    name:
    annotations:
dbmanager:
  enabled: true
  name: katib-db-manager
  image:
    repository: kubeflowkatib/katib-db-manager
    registryOverwrite:
    tagOverwrite:
    pullPolicyOverwrite:
  autoscaling:
    # If autoscaling is disabled, replica count for a component is equal to minReplicas.
    enabled:
    minReplicas:
    maxReplicas:
    targetCPUUtilizationPercentage:
    targetMemoryUtilizationPercentage:
  annotations:
    sidecar.istio.io/inject: "false"
  service:
    create: true
    annotations:
    type: ClusterIP
  database:
    type: postgres # valid values mysql, postgres
    name: postgres # Shouldn't this go into a "katib" db?
    secret:
      create: true # Set to false to manually create proper secret if no programatic secret provider is available AVP etc https://argocd-vault-plugin.readthedocs.io/en/stable/config/
      name: katib-db-secrets
      data: # Should be migrated to AVP or similar so not in plaintext
        DB_USER: a2F0aWI=  # katib
        DB_PASSWORD: a2F0aWI=  # katib
urlPrefix: /katib
istioIntegration:
  create: true
  enabled: true
  authorizationMode: ingressgateway
  gateway:
    name: kubeflow-gateway
config:
  init:
    certGenerator:
      enable: false
    controller:
      webhookPort: 8443
      trialResources:
        - Job.v1.batch
#        - TFJob.v1.kubeflow.org
#        - PyTorchJob.v1.kubeflow.org
#        - MPIJob.v1.kubeflow.org
#        - XGBoostJob.v1.kubeflow.org
#        - MXJob.v1.kubeflow.org
  runtime:
    metricsCollectors:
      - kind: StdOut
        image: docker.io/kubeflowkatib/file-metrics-collector:v0.17.0-rc.0
      - kind: File
        image: docker.io/kubeflowkatib/file-metrics-collector:v0.17.0-rc.0
      - kind: TensorFlowEvent
        image: docker.io/kubeflowkatib/tfevent-metrics-collector:v0.17.0-rc.0
        resources:
          limits:
            memory: 1Gi
    suggestions:
      - algorithmName: random
        image: docker.io/kubeflowkatib/suggestion-hyperopt:v0.17.0-rc.0
      - algorithmName: tpe
        image: docker.io/kubeflowkatib/suggestion-hyperopt:v0.17.0-rc.0
      - algorithmName: grid
        image: docker.io/kubeflowkatib/suggestion-optuna:v0.17.0-rc.0
      - algorithmName: hyperband
        image: docker.io/kubeflowkatib/suggestion-hyperband:v0.17.0-rc.0
      - algorithmName: bayesianoptimization
        image: docker.io/kubeflowkatib/suggestion-skopt:v0.17.0-rc.0
      - algorithmName: cmaes
        image: docker.io/kubeflowkatib/suggestion-goptuna:v0.17.0-rc.0
      - algorithmName: sobol
        image: docker.io/kubeflowkatib/suggestion-goptuna:v0.17.0-rc.0
      - algorithmName: multivariate-tpe
        image: docker.io/kubeflowkatib/suggestion-optuna:v0.17.0-rc.0
      - algorithmName: enas
        image: docker.io/kubeflowkatib/suggestion-enas:v0.17.0-rc.0
        resources:
          limits:
            memory: 400Mi
      - algorithmName: darts
        image: docker.io/kubeflowkatib/suggestion-darts:v0.17.0-rc.0
      - algorithmName: pbt
        image: docker.io/kubeflowkatib/suggestion-pbt:v0.17.0-rc.0
        persistentVolumeClaimSpec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
    earlyStoppings:
      - algorithmName: medianstop
        image: docker.io/kubeflowkatib/earlystopping-medianstop:v0.17.0-rc.0