database:
  type: postgres # valid values mysql, postgres
  name: katib
  secret:
    create: true # Set to false to manually create proper secret if no programatic secret provider is available AVP etc https://argocd-vault-plugin.readthedocs.io/en/stable/config/
    name: katib-db-secrets
    data:  # Should be migrated to AVP or similar so not in plaintext
      DB_USER: a2F0aWI=  # katib
      DB_PASSWORD: a2F0aWI=  # katib