apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../istio-1-17/istio-install/base

patchesStrategicMerge:
- patches/istio-configmap-disable-tracing-enable-oauth2-proxy.yaml
- patches/jwt-refresh-interval.yaml