apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../istio-1-17/istio-install/base

resources:
  - dex-requestauthentication.yaml

patchesStrategicMerge:
- patches/istio-configmap-disable-tracing-enable-oauth2-proxy.yaml
- patches/jwt-refresh-interval.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: istio-parameters
  envs:
  - params.env

vars:
- name: dex_issuer
  objref:
    kind: ConfigMap
    name: istio-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.issuer

configurations:
- params.yaml