apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: minio
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: kubeflow
  sources:
    - chart: minio
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 13.7.0
      helm:
        valueFiles:
          - $values/example/helm/values.minio.yaml
    - repoURL: https://github.com/doncorsean/kubeflow-manifests.git
      targetRevision: helmcharts
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 5
    syncOptions:
      - CreateNamespace=true
