apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: argo-kubeflow-workflows
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: argo-kubeflow-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: kubeflow
  sources:
    - chart: argo-workflows
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.17.1
      helm:
        valueFiles:
          - $values/example/helm/values.argo-workflows.yaml
    - repoURL: https://github.com/doncorsean/kubeflow-manifests.git
      targetRevision: helmcharts
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 5
    syncOptions:
      - CreateNamespace=true
