apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: knative-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: knative-operator
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: knative-operator
      repoURL: https://raw.githubusercontent.com/kromanow94/knative-operator/main
      targetRevision: v1.11.12
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 5
    syncOptions:
      - CreateNamespace=true
