apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: kserve
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  project: default
  sources:
    - repoURL: https://github.com/kserve/kserve
      targetRevision: v0.11.2
      path: charts/kserve-resources
      helm:
        valueFiles:
          - $values/example/helm/values.kserve.yaml
    - repoURL: https://github.com/kromanow94/kubeflow-manifests.git
      targetRevision: helmcharts
      ref: values
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      jqPathExpressions:
        - .webhooks[] | .clientConfig
        - .webhooks[] | .failurePolicy
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      jqPathExpressions:
        - .webhooks[] | .clientConfig
        - .webhooks[] | .failurePolicy
      kind: ValidatingWebhookConfiguration
    - group: rbac.authorization.k8s.io
      jsonPointers:
        - /rules
      kind: ClusterRole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 5
    syncOptions:
      - CreateNamespace=true
