# Secret with Object Store credentials
#
# The secret name and keys 'accesskey' and 'secretkey' are hardcoded for kubeflow pipelines:
# * <=2.1.0:
#   https://github.com/kubeflow/pipelines/blob/2.1.0/backend/src/v2/objectstore/object_store.go#L292
#   https://github.com/kubeflow/pipelines/blob/2.1.0/backend/src/v2/objectstore/object_store.go#L324
#   https://github.com/kubeflow/pipelines/blob/2.1.0/backend/src/v2/objectstore/object_store.go#L325
# * >=2.2.0 (state as of 2nd May 2024)
#   https://github.com/kubeflow/pipelines/blob/2.2.0/backend/src/v2/config/env.go#L39

# The secret keys 'root-user' and 'root-password' are required by the MySQL Bitnami Helm Chart:
# https://artifacthub.io/packages/helm/bitnami/mysql/9.21.2

apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-minio-artifact
stringData:
  accesskey: minio
  secretkey: minio123

  root-user: minio
  root-password: minio123
