apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: kubeflow
stringData:
  mysql-password: mysql1234
  mysql-root-password: mysql1234
  username: root
  host: mysql.kubeflow.svc.cluster.local
