commonLabels:
  sidecar.istio.io/inject: "false"
auth:
  existingSecret: mlpipeline-minio-artifact
networkPolicy:
  allowExternalEgress: false
  extraIngress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: app.kubernetes.io/part-of
                operator: In
                values:
                  - kubeflow-profile
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - istio-ingress
        - podSelector: {} # allow all pods from the same namespace
