istioIntegration:
  m2m:
    inCluster: false
    issuer: https://oidc.eks.<region>.amazonaws.com/id/1234567890
    selfSigned:
      autoJwksDiscovery: false

pipelines:
  config:
    db:
      user:
        secretKeyRef:
          name: db-credentials
      password:
        secretKeyRef:
          name: db-credentials
          key: mysql-root-password
      host:
        secretKeyRef:
          name: db-credentials
    objectStore:
      accessKey:
        secretKeyRef:
          name: mlpipeline-minio-artifact
      secretAccessKey:
        secretKeyRef:
          name: mlpipeline-minio-artifact

katib:
  dbmanager:
    config:
      db:
        user:
          secretKeyRef:
            name: db-credentials
            key: username
        password:
          secretKeyRef:
            name: db-credentials
            key: mysql-root-password
        host:
          secretKeyRef:
            name: db-credentials
            key: host

notebooks:
  jupyterWebApp:
    spawnerFormDefaults:
      configurations:
        value:
          - access-ml-pipeline
