istioIntegration:
#  envoyExtAuthzHttpExtensionProviderName: oauth2-proxy
  envoyExtAuthzHttpExtensionProviderName: false
  gateway:
    selector:
      app: istio-origin-gateway
      istio: origin-gateway
  servers:
    - hosts:
        - kubeflow.oceandrivegraphics.com
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - kubeflow.oceandrivegraphics.com
      port:
        name: http-443
        number: 443
        protocol: HTTPS
      tls:
        credentialName: kubeflow-tls-secret
        mode: SIMPLE
  m2m:
    inCluster: false
    issuer: https://oidc.eks.<region>.amazonaws.com/id/1234567890
    selfSigned:
      autoJwksDiscovery: false

pipelines:
  config:
    db:
      user:
        secretKeyRef:
          name: db-credentials
      password:
        secretKeyRef:
          name: db-credentials
          key: mysql-root-password
      host:
        secretKeyRef:
          name: db-credentials
    objectStore:
      accessKey:
        secretKeyRef:
          name: mlpipeline-minio-artifact
      secretAccessKey:
        secretKeyRef:
          name: mlpipeline-minio-artifact

notebooks:
  jupyterWebApp:
    spawnerFormDefaults:
      configurations:
        value:
          - access-ml-pipeline
