katib:
  enabled: true
  database:
    type: postgres # valid values mysql, postgres
auth:
  userHeaderName: kubeflow-userid
istioIntegration:
  authentication:
    enabled: true
    host: kubeflow.oceandrivegraphics.com # Used to isolate istio-ingress AuthorizationPolicy to kubeflow subdomain i.e. kubeflow.<your domain>.com

  envoyExtAuthzHttpExtensionProviderName: oauth2-proxy
  gateway:
    selector:
      app: istio-origin-gateway
      istio: origin-gateway
    servers:
      - hosts:
          - kubeflow.oceandrivegraphics.com
        port:
          name: http
          number: 80
          protocol: HTTP
        tls:
          httpsRedirect: true
      - hosts:
          - kubeflow.oceandrivegraphics.com
        port:
          name: http-443
          number: 443
          protocol: HTTPS
        tls:
          credentialName: kubeflow-tls-secret
          mode: SIMPLE
  m2m:
    inCluster: false
    issuer: https://oidc.eks.us-east-1.amazonaws.com/id/1E0598CC524467E262781D09B764C588
    selfSigned:
      autoJwksDiscovery: false

pipelines:
  config:
    db:
      user:
        secretKeyRef:
          name: db-credentials
      password:
        secretKeyRef:
          name: db-credentials
          key: mysql-root-password
      host:
        secretKeyRef:
          name: db-credentials
    objectStore:
      accessKey:
        secretKeyRef:
          name: mlpipeline-minio-artifact
      secretAccessKey:
        secretKeyRef:
          name: mlpipeline-minio-artifact

notebooks:
  jupyterWebApp:
    spawnerFormDefaults:
      configurations:
        value:
          - access-ml-pipeline
