apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kromanow94/kubeflow-manifests.git
    targetRevision: helmcharts
    path: example/helm
    directory:
      include: "app.*"
      exclude: app.app-of-apps.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 5
