apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.kubeflowRoles.kubeflowAdminRoleLabel" . | nindent 4 }}
  name: {{ include "kubeflow.katib.kfNbAdminClusterRoleName" . }}
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        {{- include "kubeflow.katib.kfNbAdminClusterRoleName" . | nindent 6 }}
rules: []
