apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy

resources:
  - namespace.yaml
  - authorizationpolicy.audience-oauth2-proxy.yaml
  - authorizationpolicy.audience-redis.yaml
  - destinationrule.redis-headless.yaml
  - destinationrule.redis-master.yaml

helmCharts:
  - name: oauth2-proxy
    repo: https://charts.bitnami.com/bitnami
    version: 3.4.0
    # version: 3.7.7
    releaseName: oauth2-proxy
    namespace: oauth2-proxy
    # valuesFile: values.yaml
    valuesFile: values.3.7.7.yaml