{{- if (include "kubeflow.katib.enabled" . | eq "true") -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-db-manager
  namespace: kubeflow
  labels:
    katib.kubeflow.org/component: db-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      katib.kubeflow.org/component: db-manager
  template:
    metadata:
      labels:
        katib.kubeflow.org/component: db-manager
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: katib-db-manager
          image: docker.io/kubeflowkatib/katib-db-manager
          envFrom:
            - secretRef:
                name: {{ .Values.database.secret.name }}
          env:
            - name: DB_NAME
              value: {{ .Values.database.name }}
          command:
            - "./katib-db-manager"
          ports:
            - name: api
              containerPort: 6789
          livenessProbe:
            grpc:
              port: 6789
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 5
{{- end }}
