{{- if (include "kubeflow.katib.dbmanager.enabled" . | eq "true") -}}

  {{- $autoscalingEnabled := include "kubeflow.katib.dbmanager.autoscaling.enabled" . -}}
  {{- $replicas := include "kubeflow.katib.dbmanager.autoscaling.minReplicas" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "kubeflow.katib.dbmanager.labels" . | nindent 4 }}
  name: {{ include "kubeflow.katib.dbmanager.name" . }}
  namespace: {{ include "kubeflow.namespace" . }}
spec:
  {{- if (eq $autoscalingEnabled "false") }}
  replicas: {{ $replicas }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "kubeflow.katib.dbmanager.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "kubeflow.katib.dbmanager.selectorLabels" . | nindent 8 }}
      {{- with .Values.dbmanager.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ include "kubeflow.katib.dbmanager.baseName" . }}
          image: {{ include "kubeflow.katib.dbmanager.image" . }} # docker.io/kubeflowkatib/katib-db-manager
          envFrom:
            - secretRef:
                name: {{ .Values.dbmanager.database.secret.name }}
          env:
            - name: DB_NAME
              value: {{ .Values.dbmanager.database.name }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbmanager.database.secret.name }}
                  key: {{ .Values.dbmanager.dbSecretPasswordKey }}
          command:
            - "./katib-db-manager"
          ports:
            - name: api
              containerPort: 6789
          livenessProbe:
            grpc:
              port: 6789
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 5
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
