---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: $(issuer)

    storage:
      type: kubernetes
      config:
        inCluster: true

    oauth2:
      skipApprovalScreen: true

    web:
      # https: 0.0.0.0:5556
      # tlsCert: /etc/dex/tls/tls.crt
      # tlsKey: /etc/dex/tls/tls.key
      # For HTTP configuration remove tls configs and add
      http: 0.0.0.0:5556

    logger:
      level: "debug"
      format: text
    
    # Must be enabled for staticPasswords
    enablePasswordDB: true
    staticPasswords:
    - email: user@example.com
      hash: $2y$12$4K/VkmDd1q1Orb3xAt82zu8gk7Ad6ReFR4LCP9UeYE90NLiN9Df72
      # https://github.com/dexidp/dex/pull/1601/commits
      # FIXME: Use hashFromEnv instead
      username: user
      userID: "15841185641784"

    staticClients:
    - id: $(application_client_id)
      redirectURIs: $(oidc_redirect_uris)
      name: 'Dex Login Application'
      secret: $(application_client_secret)
